# Generated by Django 3.0.7 on 2020-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
